# Generated by Django 2.2.28 on 2022-08-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_dasda'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='new_lambda_url',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
